flexibeast/urls.py
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

from accounts.views import CustomLoginView, data_privacy_policy, cookie_policy

from website.views import permission_denied

urlpatterns = [
    path(
        'studioadmin/', include('studioadmin.urls')
    ),
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('testimonials/', include('reviews.urls')),
    path('page-not-available/', permission_denied, name='permission_denied'),
    path('accounts/profile/', include('accounts.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico/',
        RedirectView.as_view(url=settings.STATIC_URL+'favicon.ico',
                             permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

if settings.HEROKU:  # pragma: no cover
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

urlpatterns.append(path('', include('website.urls')))

gallery/urls.py
from django.conf import settings
from django.urls import path
from gallery.views import category_detail_view, CategoryListView, \
    CategoryUpdateView, gallery_menu_view, view_gallery, gallery_website_view

app_name = 'gallery'


urlpatterns = [
    # path('', gallery_menu_view, name='gallery'),
    path('', gallery_website_view, name='gallery'),
    path('album/<slug:slug>/', category_detail_view, name='category'),
    ##### VIEWS FOR STAFF USER ONLY #####
    # Category list view, show all categories in list, allow  for edit of
    # name and delete of entire category, add new category, links to category
    # detail views
    path('albums/', CategoryListView.as_view(), name='categories'),
    # Category detail view, show all images for edit/delete/add
    path(
        'albums/<int:pk>/', CategoryUpdateView.as_view(),
        name='edit_category'
    )
]


if settings.TESTING:
    urlpatterns.append(path('alternative_view/', view_gallery, name='alternative'))

reviews/urls.py
from django.urls import path

from reviews.views import ReviewListView, ReviewCreateView, \
    ReviewUpdateView, StaffReviewListView


app_name = 'reviews'


urlpatterns = [
    path('', ReviewListView.as_view(), name='reviews'),
    ##### VIEWS FOR LOGGED IN USER ONLY #####
    # add a review
    path('add/', ReviewCreateView.as_view(), name='add_review'),
    # edit review (allow users to edit their own reviews)
    path(
      '<slug:slug>/edit/', ReviewUpdateView.as_view(), name='edit_review'
    ),
    ##### VIEWS FOR STAFF USER ONLY #####
    # listview for all reviews, button to publish/reject
    path('staff-review/', StaffReviewListView.as_view(), name='staff_reviews')
]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from django_extensions.db.fields import AutoSlugField


class Review(models.Model):

    user = models.ForeignKey(
        User, verbose_name='author', on_delete=models.CASCADE
    )
    user_display_name = models.CharField(
        max_length=255, blank=True,
        verbose_name='username that will be displayed on the site',
        help_text='If not provided, your first name will be used'
    )
    submission_date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=255, null=True, blank=True)
    review = models.TextField(verbose_name='testimonial')
    rating = models.IntegerField(default=5)
    published = models.BooleanField(default=False)

    previous_user_display_name = models.CharField(
        max_length=255, null=True, blank=True
    )
    previous_review = models.TextField(null=True, blank=True)
    previous_rating = models.IntegerField(null=True, blank=True)
    previous_title = models.CharField(max_length=255, null=True, blank=True)
    edited = models.BooleanField(default=False)
    update_published = models.BooleanField(default=False)
    edited_date = models.DateTimeField(null=True, blank=True)

    reviewed = models.BooleanField(default=False)  # flag for notifications to admin users

    slug = AutoSlugField(populate_from='title', max_length=40, unique=True)

    selected = models.BooleanField(default=False, help_text="Selected for display on home page")

    class Meta:
        ordering = ('-submission_date',)

    def approve(self):
        if not self.published:
            self.published = True
        elif not self.update_published:
            self.update_published = True
        self.reviewed = True
        self.save()

    def reject(self):
        self.reviewed = True
        if self.published and not self.edited:
            self.published = False
        elif self.update_published:
            self.update_published = False
        self.save()

    def save(self, *args, **kwargs):
        # if no user_display_name on save, make it the user's first name
        if not self.user_display_name:
            self.user_display_name = self.user.first_name

        already_exists = False
        if self.pk is not None:
            already_exists = True
            orig = Review.objects.get(pk=self.pk)

        # on save, check if user_display_name review, rating or title have
        # changed; if so, we
        # set edited to True, and copy the current values to previous
        # In templates, show the previous values if published is True but
        # update_published is False (i.e. not approved by staff yet)
        if already_exists:
            if self.review != orig.review or \
                            self.rating != orig.rating or \
                            self.title != orig.title or \
                            self.user_display_name != orig.user_display_name:
                self.edited = True
                self.edited_date = timezone.now()
                self.update_published = False
                self.previous_user_display_name = orig.user_display_name
                self.previous_review = orig.review
                self.previous_rating = orig.rating
                self.previous_title = orig.title
                self.reviewed = False

        # call super to save new object
        super(Review, self).save(*args, **kwargs)

    def __str__(self):
        return "{} - {}".format(
            self.user_display_name, self.submission_date.strftime('%d-%b-%y')
        )

reviews/forms.py
from django import forms
from django.forms.models import modelformset_factory, BaseModelFormSet
from django.utils.safestring import mark_safe


from django.core.exceptions import ValidationError

from reviews.models import Review


def validate_rating(value):
    if value < 1 or value > 5:
        raise ValidationError(
            'Rating must be between 1 and 5.'
        )


class ReviewForm(forms.ModelForm):

    rating = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'class': 'rating fa-lg',
                'data-max': '5',
                'data-min': '1',
                'data-icon-lib': 'fa',
                'data-active-icon': 'fa-star fa-lg',
                'data-inactive-icon': 'fa-star-o fa-lg',
                'name': 'rating'
            }
        ),
        initial=5,
        validators=[validate_rating],
        help_text="Click on a star to select rating"
    )

    class Meta:
        model = Review
        fields = ('user_display_name', 'title', 'rating', 'review')
        widgets = {
            'user_display_name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'title': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'review': forms.Textarea(
                attrs={'class': 'form-control'}
            ),
        }


class ReviewSortForm(forms.Form):

    order_choices = (
        ('-submission_date', 'Date submitted (most recent first)'),
        ('submission_date', 'Date submitted (earliest first)'),
        ('-rating', 'Rating (high to low)'),
        ('rating', 'Rating (low to high)'),
        ('user', 'Author name')
    )
    order = forms.ChoiceField(
        widget=forms.Select(attrs={'onchange': 'form.submit()'}),
        choices=order_choices,
        required=False
    )


class BaseReviewFormSet(BaseModelFormSet):

    def __init__(self, *args, **kwargs):
        self.previous = kwargs.pop('previous', '')
        super(BaseReviewFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = True

    def add_fields(self, form, index):
        super(BaseReviewFormSet, self).add_fields(form, index)

        if self.previous:
            # don't show option to reset to undecided if already approved or
            # rejected
            review_choices = REVIEW_CHOICES[0:2]
        else:
            review_choices = REVIEW_CHOICES

        if self.previous == 'approved':
            initial = 'approve'
        elif self.previous == 'rejected':
            initial = 'reject'
        else:
            initial = 'undecided'

        form.fields['decision'] = forms.ChoiceField(
            widget=forms.RadioSelect(attrs={'class': 'inline'}),
            choices=review_choices,
            initial=initial,
            required=False
        )

ReviewFormSet = modelformset_factory(
    Review,
    fields=('id',),
    extra=0,
    formset=BaseReviewFormSet,
    can_delete=False
)


REVIEW_CHOICES = (
  ('approve', mark_safe('<span class="fa fa-thumbs-up fa-lg" alt="approve" title="approve">')),
  ('reject', mark_safe('<span class="fa fa-thumbs-down fa-lg" alt="reject" title="reject">')),
  ('undecided', mark_safe('<span class="fa fa-question-circle fa-lg" alt="undecided" title="undecided">')),
)

reviews/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q

from braces.views import LoginRequiredMixin

from activitylog.models import ActivityLog

from reviews.forms import ReviewForm, ReviewFormSet, ReviewSortForm
from reviews.models import Review
from reviews.utils import StaffUserMixin


class ReviewListView(ListView):

    template_name = 'reviews/reviews.html'
    context_object_name = 'reviews'
    model = Review

    def get_queryset(self):
        return Review.objects.filter(published=True).order_by('-submission_date')

    def get_context_data(self, *args, **kwargs):
        context = super(ReviewListView, self).get_context_data()
        if not self.request.user.is_anonymous:
            user_reviews = Review.objects.filter(user=self.request.user)
            context['user_reviews'] = user_reviews

        order = self.request.GET.get('order', '')
        form = ReviewSortForm(initial={'order': order})
        context['order_sort_form'] = form
        if order:
            context['reviews'] = self.get_queryset().order_by(order)
        context['nav_section'] = 'more'
        return context


class ReviewCreateView(LoginRequiredMixin, CreateView):

    template_name = 'reviews/add_edit_review.html'
    context_object_name = 'review'
    model = Review
    form_class = ReviewForm

    def form_valid(self, form):
        review = form.save(commit=False)
        review.user = self.request.user
        review.save()
        ActivityLog.objects.create(
            log="Testimonial (id {}) submitted by {}".format(
                review.id, review.user.username
            )
        )
        messages.success(self.request, 'Your testimonial has been submitted and will be '
                              'displayed on the site shortly')
        return HttpResponseRedirect(reverse('reviews:reviews'))

    def form_invalid(self, form):
        messages.error(self.request, "Please correct the errors below")
        return super(ReviewCreateView, self).form_invalid(form)


class ReviewUpdateView(LoginRequiredMixin, UpdateView):

    template_name = 'reviews/add_edit_review.html'
    context_object_name = 'review'
    model = Review
    form_class = ReviewForm

    def dispatch(self, request, *args, **kwargs):
        review = self.get_object()
        if request.user.is_authenticated and review.user != request.user:
            return HttpResponseRedirect(settings.PERMISSION_DENIED_URL)
        return super(ReviewUpdateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        ActivityLog.objects.create(
            log="Testimonial (id {}) updated by {}".format(
                form.instance.id, form.instance.user.username
            )
        )
        messages.success(self.request, 'Your testimonial has been updated and '
                                        'will be displayed on the site shortly')

        return HttpResponseRedirect(reverse('reviews:reviews'))
    
    def form_invalid(self, form):
        messages.error(self.request, "Please correct the errors below")
        return super(ReviewUpdateView, self).form_invalid(form)


class StaffReviewListView(StaffUserMixin, ListView):

    template_name = 'reviews/staff_reviews.html'
    context_object_name = 'reviews'
    model = Review

    def dispatch(self, request, *args, **kwargs):
        self.previous = request.GET.getlist('view', [''])[0]
        return super(StaffReviewListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if self.previous == 'approved':
            # review is approved if it's been reviewed AND is published and
            # hasn't been edited OR has been edited and update_published is true
            queryset = Review.objects.filter(
                Q(reviewed=True),
                Q(published=True, edited=False) |
                Q(update_published=True, edited=True)
            )
        elif self.previous == 'rejected':
            # review is rejected if it's been reviewed AND is not published OR
            # has been edited and update_published is false
            queryset = Review.objects.filter(
                Q(reviewed=True),
                Q(published=False) |
                Q(update_published=False, edited=True)
            )
        else:
            queryset = Review.objects.filter(reviewed=False)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(StaffReviewListView, self).get_context_data()
        context['review_formset'] = ReviewFormSet(
            queryset=self.get_queryset(), previous=self.previous
        )
        context['showing_previous'] = self.previous
        return context

    def post(self, request):

        review_formset = ReviewFormSet(request.POST)

        view = request.GET.getlist('view', [''])[0]
        # if we are viewing approved or rejected, we can ignore the decision
        # unless it is the opposite
        change = False

        if review_formset.has_changed():
            for form in review_formset:
                if form.is_valid():
                    if form.has_changed() and 'decision' in form.changed_data:
                        review = form.save(commit=False)
                        decision = form.cleaned_data.get('decision')

                        if decision == 'approve' and view != 'approved':
                            review.approve()
                            messages.success(
                                request, 'Review from user {} {} has been '
                                         'approved'.format(
                                    review.user.first_name,
                                    review.user.last_name
                                )
                            )
                            change = True
                            ActivityLog.objects.create(
                                log="Testimonial{} (id {}) approved by {}".format(
                                    " update" if review.edited else "",
                                    review.id, request.user.username
                                )
                            )
                        elif decision == 'reject' and view != 'rejected':
                            review.reject()
                            messages.success(
                                request, 'Review from user {} {} has been '
                                         'rejected'.format(
                                    review.user.first_name,
                                    review.user.last_name
                                )
                            )
                            change = True
                            ActivityLog.objects.create(
                                log="Testimonial{} (id {}) rejected "
                                    "by {}".format(
                                    " update" if review.edited else "",
                                    review.id, request.user.username
                                )
                            )

                        review.save()
            review_formset.save()

        if not change:
            messages.info(request, 'No changes made')

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('reviews:staff_reviews')

reviews/templates/reviews/add_edit_review.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}<link rel="stylesheet" href="{% static 'reviews/css/reviews.css' %}">{% endblock %}

{% block content %}

    <section>
<div class="container">
    <div class="row">
       <div class="center wow fadeInDown">
            <h2>
                {% if review %}
                    Edit testimonial
                {% else %}
                    Add new testimonial
                {% endif %}
            </h2>
        </div>
        <div class="col-sm-12">
        {% if form.instance.edited and not form.instance.reviewed and not form.instance.update_published %}
            <p>The form below shows a submitted update which is still pending review.</p>
        {% elif form.instance.edited and form.instance.reviewed and not form.instance.update_published %}
            <p>The form below shows a submitted update which has not been accepted. You
                may edit and resubmit it for review if you wish.</p>
        {% endif %}
            <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                <label>{{ field.label }}{% if field.field.required %}*{% endif %}</label>
                    <div {% if field.errors %}class='form-error'{% endif %}>{{ field }}</div>
                    {% if field.errors %}<span class="form-error">{{ field.errors }}</span>{% endif %}<br>
                    <div class="review-help">{{ field.help_text }}</div><br>
                {% endfor %}

                <button type="submit" class="btn btn-fb-success-minor">Submit</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'reviews/js/bootstrap-rating-input.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'reviews/js/reviews.js' %}" type="text/javascript"></script>
{% endblock %}

reviews/templates/reviews/ratings.html
{% for rating in rating_list %}
    {% if rating == 1 %}
        <span class="fa fa-star"></span>
    {% else %}
        <span class="fa fa-star-o"></span>
    {% endif %}
{% endfor %}

reviews/templates/reviews/reviews.html
{% extends "base.html" %}
{% load static %}
{% load reviewtags %}

{% block extra_head %}<link rel="stylesheet" href="{% static 'reviews/css/reviews.css' %}">{% endblock %}

{% block content %}
    <section>
    <div class="container">
    <div class="row">
        <div class="center wow fadeInDown">
            <h1>
                Testimonials
            </h1>
        </div>

        <div>

            <div class="col-sm-6 pull-right">
                {% if user.is_authenticated %}
                    <a class="btn btn-fb-success-minor btn-fb-success-minor-sm pull-right" href="{% url 'reviews:add_review' %}">Add a testimonial</a>
                {% else %}
                    <a class="btn btn-fb-success-minor btn-fb-success-minor-sm" href="{% url 'account_login' %}?next={{request.get_full_path}}"><div>Sign in</div></a> to add a testimonial
                {% endif %}
            </div>
            <div class="col-sm-6 pull-left">
                <form class='reviews-filter' action="" method="get">
                    <strong>{{ order_sort_form.order }}</strong>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        {% if reviews %}
        {% for review in reviews %}
        <div class="col-sm-12 review {% if forloop.last %}last{% endif %}">
            <div class="col-sm-2">
                <p>
                    {% show_rating review.rating %}<br>
                    <span class="fa fa-user"></span> {{ review.user_display_name }}<br>
                     <span class="review-date">
                    {% if review.edited and review.update_published %}
                        {{ review.edited_date|date:'d M Y' }}
                    {% else %}
                        {{ review.submission_date|date:'d M Y' }}<br>
                    {% endif %}</span>

                    {% if review in user_reviews %}
                        <div><a href="{% url 'reviews:edit_review' review.slug %}"><div class="btn btn-fb-success-minor btn-fb-success-minor-sm">Edit</div></a></div>
                    {% endif %}
                </p>
            </div>
            <div class="col-sm-10 wow fadeInDown"><h4>
                {% if not review.edited or review.update_published %}
                        {{ review.title }}
                {% else %}
                    {{ review.previous_title }}
                {% endif %}
            </h4>
            <p>
                {% if not review.edited or review.update_published %}
                    {{ review.review|linebreaksbr }}
                {% else %}
                    {{ review.previous_review|linebreaksbr }}
                {% endif %}
            </p>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="col-sm-12">No testimonials available to view.</div>
    {% endif %}
    </div> <!-- row -->
    </div> <!-- container -->
    </section>
{% endblock %}

{% block extra_scripts %}{% endblock %}

reviews/templates/reviews/staff_reviews.html
{% extends "base.html" %}
{% load static %}
{% load reviewtags %}

{% block extra_head %}<link rel="stylesheet" href="{% static 'reviews/css/reviews.css' %}">{% endblock %}

{% block content %}
    <div class="container container-fluid">
    <div class="page-header col-sm-12">
        <h1>
            Testimonials for Review
        </h1>
    </div>
    <div class="col-sm-12"><p>Changed/new data is shown in <span class="review-changed">red</span></p></div>
        <div class="row">
            <div class="col-sm-12">
                <form class="form-horizontal" method="post" action="">
                    {% csrf_token %}
                    <div>
                        <div>
                            <a class="btn btn-warning reviews-btn filter-btn {% if showing_previous == 'approved' %}disabled{% endif %}" href="{% url 'reviews:staff_reviews' %}?view=approved">View approved</a>
                            <a class="btn btn-warning reviews-btn filter-btn {% if showing_previous == 'rejected' %}disabled{% endif %}" href="{% url 'reviews:staff_reviews' %}?view=rejected">View rejected</a>
                            <a class="btn btn-warning reviews-btn filter-btn {% if not showing_previous %}disabled{% endif %}" href="{% url 'reviews:staff_reviews' %}">View pending</a>
                        </div>
                        <span class="divider"></span>

                        {{ review_formset.management_form }}
                        {% for review in review_formset %}
                            <span class=hide>{{ review.id }}</span>
                            <h4>Testimonial from {{ review.instance.user.first_name }} {{ review.instance.user.last_name }} ({{ review.instance.user.username }})</h4>
                            <p>Last submission on {% if review.instance.edited_date %}{{ review.instance.edited_date | date:'d M Y' }}{% else %}{{ review.instance.submission_date | date:'d M Y' }}{% endif %}</p>
                            <div class="col-sm-6">
                            <h4>{% if showing_previous == 'approved' %}Previous version{% else %}Last approved version{% endif %}</h4>
                            {% if review.instance.previous_rating %}
                                <label>Author's display name:</label><p>{{ review.instance.previous_user_display_name }}</p>
                                <label>Title:</label><p>{{ review.instance.previous_title }}</p>
                                <label>Rating:</label><p>{% show_rating review.instance.previous_rating %}</p>
                                <label>Testimonial content:</label><p>{{ review.instance.previous_review }}</p>
                            {% else %}
                                <p>N/A</p>
                            {% endif %}
                            </div>
                            <div class="col-sm-6">
                            <h4>{% if showing_previous == 'approved' %}Current approved version{% elif showing_previous == 'rejected' %}Rejected version
                                {% elif review.instance.previous_rating %}New version{% else %}New submission{% endif %}</h4>
                                <label>Author's display name:</label>
                                <p>
                                    <span {% if review.instance.user_display_name != review.instance.previous_user_display_name %}class="review-changed"{% endif %}>{{ review.instance.user_display_name }}</span>
                                </p>
                                <label>Title:</label>
                                    <p>
                                        <span {% if review.instance.title != review.instance.previous_title %}class="review-changed"{% endif %}>{{ review.instance.title }}</span>
                                    </p>
                                <label>Rating:</label>
                                    <p>
                                        <span {% if review.instance.rating != review.instance.previous_rating %}class="review-changed"{% endif %}>{% show_rating review.instance.rating %}</span>
                                    </p>
                                <label>Testimonial content:</label>
                                    <p>
                                        <span {% if review.instance.review != review.instance.previous_review %}class="review-changed"{% endif %}>{{ review.instance.review }}</span>
                                    </p>
                            </div>
                            <div class="col-sm-12 section-end"><label>Approve/Reject: </label><br>{{ review.decision }}</div>
                            <div class="divider"></div>
                        {% endfor %}
                        {% if review_formset.forms %}<div><input class="btn btn-success" name="formset_submitted" type="submit" value="Save" /></div>{% endif %}


                    {% if not review_formset.forms %}
                        <br><br>
                        <div class="col-sm-12">
                            {% if showing_previous == 'rejected' %}
                                No rejected testimonals to display
                            {% elif showing_previous == 'approved' %}
                                No approved testimonals to display
                            {% else %}
                                No testimonials pending review
                            {% endif %}
                        </div>
                    {% endif %}
                    </div>

                </form>
             </div>


        </div>

</div>
{% endblock %}

{% block extra_scripts %}{% endblock %}