flexibeast/urls.py
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

from accounts.views import CustomLoginView, data_privacy_policy, cookie_policy

from website.views import permission_denied

urlpatterns = [
    path(
        'studioadmin/', include('studioadmin.urls')
    ),
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('testimonials/', include('reviews.urls')),
    path('page-not-available/', permission_denied, name='permission_denied'),
    path('accounts/profile/', include('accounts.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico/',
        RedirectView.as_view(url=settings.STATIC_URL+'favicon.ico',
                             permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

if settings.HEROKU:  # pragma: no cover
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

urlpatterns.append(path('', include('website.urls')))

gallery/urls.py
from django.conf import settings
from django.urls import path
from gallery.views import category_detail_view, CategoryListView, \
    CategoryUpdateView, gallery_menu_view, view_gallery, gallery_website_view

app_name = 'gallery'


urlpatterns = [
    # path('', gallery_menu_view, name='gallery'),
    path('', gallery_website_view, name='gallery'),
    path('album/<slug:slug>/', category_detail_view, name='category'),
    ##### VIEWS FOR STAFF USER ONLY #####
    # Category list view, show all categories in list, allow  for edit of
    # name and delete of entire category, add new category, links to category
    # detail views
    path('albums/', CategoryListView.as_view(), name='categories'),
    # Category detail view, show all images for edit/delete/add
    path(
        'albums/<int:pk>/', CategoryUpdateView.as_view(),
        name='edit_category'
    )
]


if settings.TESTING:
    urlpatterns.append(path('alternative_view/', view_gallery, name='alternative'))

studioadmin/urls.py
from django.urls import include, path, re_path
from django.views.generic import RedirectView

from gallery.views import CategoryListView, CategoryUpdateView
from studioadmin.views.activitylog import ActivityLogListView
from studioadmin.views.email_users import choose_users_to_email, \
    email_users_view
from studioadmin.views.timetable import WeeklySessionListView, \
    EventListView, WeeklySessionEditView, EventEditView, \
    CreateWeeklySessionView, CreateEventView
from studioadmin.views.users import UserListView
from studioadmin.views.website import PageListView, PageCreateView, \
    PageUpdateView


app_name = 'studioadmin'


urlpatterns = [
    path('users/', UserListView.as_view(), name="users"),
    path('users/email/', choose_users_to_email, name="choose_email_users"),
    path('users/email/emailform/', email_users_view,
        name="email_users_view"),
    path(
        'activitylog/', ActivityLogListView.as_view(), name='activitylog'
    ),
    #### GALLERY #####
    path(
        'gallery/albums/', CategoryListView.as_view(),
        name='gallery_categories'
    ),
    # Category detail view, show all images for edit/delete/add
    path(
        'gallery/albums/<int:pk>', CategoryUpdateView.as_view(),
        name='gallery_category_edit'
    ),
    #### WEBSITE PAGES #####
    path(
        'website-pages/',
        PageListView.as_view(), name='website_pages_list'
    ),
    path(
        'website-pages/new/', PageCreateView.as_view(), name='add_page'
    ),
    re_path(
        r'^website-pages/(?P<name>[\w\d//-]+)$',
        PageUpdateView.as_view(), name='edit_page'
    ),
    path(
        '',
        RedirectView.as_view(url='/studioadmin/classes/', permanent=True)
    ),
    #### TIMETABLE #####
    path(
        'timetable/regular-classes/',
        WeeklySessionListView.as_view(), name='timetable_sessions_list'
    ),
    path(
        'timetable/regular-classes/new',
        CreateWeeklySessionView.as_view(), name='timetable_session_add'
    ),
    path(
        'timetable/stretch-clinics/',
        EventListView.as_view(event_type='clinic'),
        name='timetable_clinics_list'
    ),
    path(
        'timetable/workshops/', EventListView.as_view(event_type='workshop'),
        name='timetable_workshops_list'
    ),
    path(
        'timetable/(<str:event_type>/new',
        CreateEventView.as_view(), name='timetable_event_add'
    ),
    path(
        'timetable/sessionedit/<int:pk>/',
        WeeklySessionEditView.as_view(), name='sessionedit'
    ),
    path(
        'timetable/edit/<int:pk>/',
        EventEditView.as_view(), name='eventedit'
    ),
]

gallery/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from django_extensions.db.fields import AutoSlugField

from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    slug = AutoSlugField(populate_from='name', max_length=40, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Image(models.Model):

    photo = ProcessedImageField(
        upload_to='gallery',
        format='JPEG',
        options={'quality': 70},
        null=True, blank=True,
    )

    thumbnail = ImageSpecField(source='photo',
                                      processors=[ResizeToFill(150, 150)],
                                      format='JPEG',
                                      options={'quality': 100})

    category = models.ForeignKey(
        Category, related_name='images', on_delete=models.CASCADE
    )
    caption = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return "Photo id: " + str(self.id)

    def save(self, *args, **kwargs):
        # delete old image file when replacing by updating the file
        try:
            this = Image.objects.get(id=self.id)
            if this.photo != self.photo:
                this.photo.delete(save=False)
        except Image.DoesNotExist:
            pass  # when new photo then we do nothing, normal case
        super(Image, self).save(*args, **kwargs)


@receiver(pre_delete)
def delete_image(sender, instance, **kwargs):
    if sender == Image:
        instance.photo.delete()

gallery/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.template.response import TemplateResponse
from django.utils.safestring import mark_safe

from activitylog.models import ActivityLog

from gallery.forms import CategoryForm, CategoriesFormset, ImageFormset
from gallery.models import Category, Image
from gallery.utils import StaffUserMixin


def gallery_website_view(request):
    categories = Category.objects.all().order_by('name')
    images = Image.objects.all()
    return TemplateResponse(
        request,
        'website/gallery.html',
        {
            'categories': categories,
            'images': images,
            'nav_section': 'gallery'
        }
    )

def view_gallery(request):
    categories = Category.objects.all().order_by('name')
    category_choice = request.GET.getlist('category', ['All'])[0]
    if category_choice == 'All':
        images = Image.objects.all()
        cat_selection = 'All'
    else:
        images = Image.objects.filter(category__id=int(category_choice))
        cat_selection = Category.objects.get(id=int(category_choice))

    return render(
        request,
        'gallery/gallery.html',
        {
            'cat_selection': cat_selection,
            'categories': categories,
            'images': images,
            'total_image_count': Image.objects.all().count()
        }
    )


def gallery_menu_view(request):
    categories = Category.objects.all().order_by('name')
    return TemplateResponse(
        request,
        'gallery/gallery_menu.html',
        {
            'categories': categories,
        }
    )


def category_detail_view(request, slug):

    category = get_object_or_404(Category, slug=slug)
    return TemplateResponse(
        request,
        'gallery/gallery_category.html',
        {
            'category': category,
            'images': category.images.all(),
            'sidenav_selection': 'gallery'
        }
    )


class CategoryListView(StaffUserMixin, ListView):

    model = Category
    template_name = 'gallery/categories.html'
    context_object_name = 'categories'

    def get_context_data(self):
        context = super(CategoryListView, self).get_context_data()
        context['categories_formset'] = CategoriesFormset()
        context['sidenav_selection'] = 'gallery'
        return context

    def post(self, request, *args, **kwargs):
        categories_formset = CategoriesFormset(request.POST)

        if categories_formset.is_valid():
            if categories_formset.has_changed():

                deleted_categories = []
                updated_categories = {}
                new_categories = []
                update_desc_msg = ""

                for form in categories_formset:
                    if form.is_valid():
                        if form.has_changed():
                            if 'DELETE' in form.changed_data:
                                category = Category.objects.get(id=form.instance.id)
                                deleted_categories.append(category.name)
                                category.delete()
                            else:
                                new = False
                                try:
                                    new_cat = form.save(commit=False)
                                    old_cat = Category.objects.get(id=new_cat.id)
                                except Category.DoesNotExist:  # creating a new category
                                    new = True

                                if 'name' in form.changed_data:
                                    if not new:
                                        old_name = old_cat.name
                                        new_name = new_cat.name
                                        updated_categories[new_cat.id] = [old_name, new_name]
                                    else:
                                        new_categories.append(new_cat.name)
                                elif 'description' in form.changed_data:
                                    if not new:
                                        update_desc_msg = "Category {}'s description " \
                                                          "has been updated".format(
                                            new_cat.name
                                        )
                                form.save()

                del_msg = ""
                upd_msg = ""
                new_msg = ""

                if len(deleted_categories) == 1:
                    del_msg = "Category '{}' and all associated images have been " \
                          "deleted".format(deleted_categories[0])
                elif len(deleted_categories) > 1:
                    del_msg = "Categories {} and all associated images have been " \
                          "deleted".format(
                        ', '.join(["'{}'".format(name) for name in deleted_categories])
                    )
                if updated_categories:
                    upd_msg = "Category names changed: {}".format(
                        ', '.join(
                            ["'{}' changed to '{}'".format(val[0], val[1])
                             for key, val in updated_categories.items()]
                        )
                    )
                if len(new_categories) == 1:
                    new_msg = "Category '{}' has been created".format(new_categories[0])
                elif len(new_categories) > 1:
                    del_msg = "Categories {} have been created".format(
                        ', '.join(["'{}'".format(name) for name in new_categories])
                    )

                messages.success(
                    request,
                    mark_safe(
                        "{}{}{}".format(
                            "{}</br>".format(del_msg) if del_msg else "",
                            "{}</br>".format(upd_msg) if upd_msg else "",
                            "{}</br>".format(update_desc_msg) if update_desc_msg else "",
                            "{}".format(new_msg)
                        )
                    )
                )

                if del_msg:
                    ActivityLog.objects.create(
                        log=del_msg + 'by admin user {}'.format(request.user)
                    )
                if upd_msg:
                    ActivityLog.objects.create(
                        log=upd_msg + 'by admin user {}'.format(request.user)
                    )
                if new_msg:
                    ActivityLog.objects.create(
                        log=new_msg + 'by admin user {}'.format(request.user)
                    )

            else:
                messages.info(request, "No changes made")

        else:
            messages.error(request, "Please correct the errors below")
            return TemplateResponse(
                request, self.template_name,
                {'categories_formset': categories_formset}
            )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('gallery:categories')


class CategoryUpdateView(StaffUserMixin, UpdateView):

    model = Category
    template_name = 'gallery/category_update.html'
    context_object_name = 'category'
    form_class = CategoryForm

    def get_object(self):
        queryset = Category.objects.all()
        return get_object_or_404(queryset, id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)

        picture_formset = ImageFormset(instance=self.get_object())
        context['image_formset'] = picture_formset
        return context

    def post(self, request, *args, **kwargs):
        category = Category.objects.get(id=self.kwargs['pk'])
        form = CategoryForm(request.POST, instance=category)
        image_formset = ImageFormset(
            request.POST, request.FILES, instance=category
        )

        if form.is_valid() and image_formset.is_valid():

            change_messages = []
            deleted_pics = []
            new_pics = []
            edited_pics = []

            if image_formset.has_changed():
                for form in image_formset.forms:
                    if form.is_valid():
                        image = form.save(commit=False)

                        if 'DELETE' in form.changed_data:
                            name = image.photo.name
                            image.delete()
                            change_messages.append(
                                'Picture {} deleted from "{}" category'.format(
                                    name.split('/')[-1],
                                    category.name.title()
                                )
                            )
                            deleted_pics.append(name.split('/')[-1])
                        elif form.has_changed():
                            action = 'edited' if image.id else 'added'
                            image.save()
                            change_messages.append(
                                'Picture {} has been {}'.format(
                                    image.photo.name.split('/')[-1],
                                    action
                                )
                            )
                            if action == 'edited':
                                edited_pics.append(
                                    image.photo.name.split('/')[-1]
                                )
                            else:
                                new_pics.append(image.photo.name.split('/')[-1])
                    else:
                        for error in form.errors:

gallery/templates/gallery/categories.html
{% extends "studioadmin/base.html" %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'gallery/css/gallery.css' %}">
{% endblock %}

{% block studioadmincontent %}

<div class="studioadmin-container">

        <h2>
            Gallery Albums
        </h2>

                    <form class="form-horizontal" method="post" action="">
                    {% csrf_token %}
                    <div class="table-responsive">
                        <table class="table tablesorter" id="sortTable">
                            <thead>
                            <tr class="success">
                                <th>Album Name</th>
                                <th>Description</th>
                                <th class="table-center">Number of images</th>
                                <th class="table-center">Add/edit images</th>
                                <th class="table-center">Delete album</br>and all attached images</th>
                            </tr>
                            </thead>
                            <tbody>

                            {{ categories_formset.management_form }}
                            {% for category in categories_formset %}
                                <span class=hide>{{ category.id }}</span>
                                {% if not category.instance.id %}
                                    <tr>
                                        <td class="gallery-tbl" colspan="5"><strong>Add New Album:</strong></td>
                                    </tr>
                                {% endif %}
                                <tr>
                                    <td class="gallery-tbl"><span {% if category.name.errors %}class="form-error"{% endif %}>{{ category.name }} {{ category.name.errors }}</span></td>
                                    <td class="gallery-tbl"><span {% if category.description.errors %}class="form-error"{% endif %}>{{ category.description }}{{ category.description.errors }}</span></td>
                                    <td class="gallery-tbl table-center" {% if category.instance.id %}id="cat_{{ category.instance.id }}_imagecount"{% endif %}>{% if category.instance.id %}{{ category.image_count }}{% endif %}</td>
                                    <td class="gallery-tbl table-center">{% if category.instance.id %}
                                        <a href="{% url 'studioadmin:gallery_category_edit' category.instance.id %}">
                                            <span class="fa fa-pencil-square-o fa-lg"></span>
                                        </a>
                                        {% endif %}
                                    </td>
                                    <td class="gallery-tbl table-center">{{ category.DELETE }}<label for={{ category.DELETE_id }}></label>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td class="gallery-tbl" colspan="5"><input class="btn btn-success" name="formset_submitted" type="submit" value="Save changes" /></td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                    </form>

</div>



{%  endblock %}


{% block extra_scripts %}
    <script src="{% static 'gallery/js/gallery.js' %}"></script>
{% endblock %}

gallery/templates/gallery/gallery_category.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}<link rel="stylesheet" href="{% static 'gallery/css/gallery.css' %}">{% endblock %}

{% block content %}

<div class="row container">
    <div class="col-sm-12">
        <h1>
            <a href="{% url 'gallery:gallery' %}">Gallery</a>: {{ category }}
        </h1>

            <h4>{% if category.description %}{{ category.description }}{% endif %}</h4>

    {% if user.is_staff %}
            <p>STAFF USERS ONLY: <a href="{% url 'gallery:edit_category' category.id %}">Edit this album</a></p>
        {% endif %}
    </div>

    <span class="divider"></span>


    {% if images %}
        <p class="gallery-help">Click on thumbnails to enlarge</p>
            <div class="col-sm-8 col-md-9">

                    {% for image in images %}
                        <div class="col-lg-3 col-md-4 col-xs-6">
                        <a href="#"
                           class="gallery-thumbnail"
                           data-image-id=""
                           data-toggle="modal"
                           data-title="{{ image.category }}"
                           data-caption="{{ image.caption }}"
                           data-image="{{ MEDIA_URL }}{{ image.photo.name }}"
                           data-target="#image-gallery">
                            <div class="thumbnail-container">
                                <img
                                     src="{{ MEDIA_URL }}{{ image.photo.name }}"
                                     alt="{{ image.photo.name }}">
                            </div>
                        </a>
                    </div>
                    {% endfor %}

                <div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title" id="image-gallery-title"></h4>
                            </div>
                            <div class="modal-body">
                                <img id="image-gallery-image" class="img-responsive" src="">
                            </div>
                            <div class="modal-footer">

                                <div class="pull-left">
                                    <button type="button" class="btn btn-gallery btn-modal" id="show-previous-image">Previous</button>
                                </div>

                                <div class="col-xs-8 text-justify" id="image-gallery-caption">
                                    This text will be overwritten by jQuery
                                </div>

                                <div class="pull-right">
                                    <button type="button" id="show-next-image" class="btn btn-gallery btn-modal">Next</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    {% else %}
    <div class="col-sm-12">No photos in this album yet</div>

    {% endif %}

</div>



{%  endblock %}


{% block extra_scripts %}
    <script src="{% static 'gallery/js/gallery.js' %}"></script>
{% endblock %}

gallery/templates/gallery/gallery_menu.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}<link rel="stylesheet" href="{% static 'gallery/css/gallery.css' %}">{% endblock %}

{% block content %}

<div class="row container">
    <div class="page-header col-sm-12">
        <h1>
            Gallery
        </h1>
        <p>Click on an album to see more</p>

        {% if user.is_staff %}
            <p>STAFF USERS ONLY: <a href="{% url 'gallery:categories' %}">View and edit Gallery</a></p>
        {% endif %}
    </div>

    {% if categories %}

        <div class="row">
            {% for category in categories %}
                {% if category.images.exists %}
                    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5">
                        <div>
                            <a href="{% url 'gallery:category' category.slug %}">
                                <div class="category thumbnail-container">
                                    {% for image in category.images.all %}
                                        {% if forloop.counter0 == 0 %}
                                            <img class="img-top-left"
                                                 src="{{ MEDIA_URL }}{{ image.photo.name }}"
                                                 alt="{{ image.photo.name }}">
                                        {% elif forloop.counter0 == 1 %}
                                            <img class="img-top-right"
                                                 src="{{ MEDIA_URL }}{{ image.photo.name }}"
                                                 alt="{{ image.photo.name }}">
                                        {% elif forloop.counter0 == 2 %}
                                            <img class="img-bottom-left"
                                                 src="{{ MEDIA_URL }}{{ image.photo.name }}"
                                                 alt="{{ image.photo.name }}">
                                        {% elif forloop.counter0 == 3 %}
                                            <img class="img-bottom-right"
                                                 src="{{ MEDIA_URL }}{{ image.photo.name }}"
                                                 alt="{{ image.photo.name }}">
                                        {% endif %}
                                    {% endfor %}
                                    {% if category.images.count < 4 %}
                                        {% if category.images.count <= 3 %}
                                            <img class="img-bottom-right"
                                                     src="{% static 'gallery/images/logo.png' %}"
                                                     alt="placeholder logo image">
                                        {% endif %}
                                        {% if category.images.count <= 2 %}
                                            <img class="img-bottom-left"
                                                     src="{% static 'gallery/images/logo.png' %}"
                                                     alt="placeholder logo image">
                                        {% endif %}
                                        {% if category.images.count == 1 %}
                                            <img class="img-top-right"
                                                     src="{% static 'gallery/images/logo.png' %}"
                                                     alt="placeholder logo image">
                                        {% endif %}
                                    {% endif %}
                                    </div>
                            </a>
                        </div>
                        <div class="category-caption"><strong>{{ category.name }}</strong></div>
                    </div>

                {% else %}
                    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-5">
                        <div class="category thumbnail-container no-photos">
                            No photos in this album yet
                        </div>
                        <div class="category-caption"><strong>{{ category.name }}</strong></div>
                    </div>

                {% endif %}
            {% endfor %}
        </div>

    {% else %}
        <div class="col-sm-12">Coming soon</div>

    {% endif %}

</div>



{%  endblock %}

gallery/templates/gallery/image_thumbnail.html
{# image_thumbnail.html #}

{% load i18n %}

{% include 'django/forms/widgets/clearable_file_input.html' %}
    <div>
            {% if widget.value.url %}
                <div class="row">
                    <div class="col-xs-2">
                        <label>File name:</label> {{ widget.value.name }}</br>
                        <img src="{{ widget.value.url }}"
                            alt="{{ widget.value }}" class="img-thumbnail gallery-update-thumbnail"/>
                    </div>
                </div>

            {% endif %}

        </div>