flexibeast/urls.py
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

from accounts.views import CustomLoginView, data_privacy_policy, cookie_policy

from website.views import permission_denied

urlpatterns = [
    path(
        'studioadmin/', include('studioadmin.urls')
    ),
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('testimonials/', include('reviews.urls')),
    path('page-not-available/', permission_denied, name='permission_denied'),
    path('accounts/profile/', include('accounts.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico/',
        RedirectView.as_view(url=settings.STATIC_URL+'favicon.ico',
                             permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

if settings.HEROKU:  # pragma: no cover
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

urlpatterns.append(path('', include('website.urls')))

gallery/urls.py
from django.conf import settings
from django.urls import path
from gallery.views import category_detail_view, CategoryListView, \
    CategoryUpdateView, gallery_menu_view, view_gallery, gallery_website_view

app_name = 'gallery'


urlpatterns = [
    # path('', gallery_menu_view, name='gallery'),
    path('', gallery_website_view, name='gallery'),
    path('album/<slug:slug>/', category_detail_view, name='category'),
    ##### VIEWS FOR STAFF USER ONLY #####
    # Category list view, show all categories in list, allow  for edit of
    # name and delete of entire category, add new category, links to category
    # detail views
    path('albums/', CategoryListView.as_view(), name='categories'),
    # Category detail view, show all images for edit/delete/add
    path(
        'albums/<int:pk>/', CategoryUpdateView.as_view(),
        name='edit_category'
    )
]


if settings.TESTING:
    urlpatterns.append(path('alternative_view/', view_gallery, name='alternative'))

timetable/urls.py
from django.urls import path
from timetable.views import toggle_spaces, EventListView, \
    WeeklySessionListView


app_name = 'timetable'


urlpatterns = [
    path('regular-classes/', WeeklySessionListView.as_view(), name='timetable'),
    path(
        'stretch-clinics/', EventListView.as_view(event_type='clinic'),
        name='timetable_clinics'),
    path(
        'workshops/', EventListView.as_view(event_type='workshop'),
        name='timetable_workshops'),
    path(
        '<int:session_id>/spaces/', toggle_spaces, name='toggle_spaces'
    ),

]

website/urls.py
from django.urls import path, re_path

from website.views import about, classes, contact, home, page, \
    privacy_policy, restricted_page_not_logged_in, retreats, \
    stretch_clinics, workshops


app_name = 'website'


urlpatterns = [
    path('contact/', contact, name='contact'),
    path(
        'login-required/', restricted_page_not_logged_in,
        name='restricted_page_not_logged_in'
    ),
    path('about/', about, name='about'),
    path('classes/', classes, name='classes'),
    path('stretch-clinics/', stretch_clinics, name='stretch_clinics'),
    path('workshops/', workshops, name='workshops'),
    path('retreats/', retreats, name='retreats'),
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    re_path(r'^(?P<page_name>[\w\d//-]+)/$', page, name='page'),
    # path('', page, {'page_name': 'about'}, name='about'),
    path('', home, name='home'),
]

studioadmin/views/timetable.py
import logging

from django.contrib import messages
from django.urls import reverse
from django.shortcuts import HttpResponse, HttpResponseRedirect, \
    get_object_or_404, render
from django.views.generic import CreateView, ListView, UpdateView
from braces.views import LoginRequiredMixin

from activitylog.models import ActivityLog

from studioadmin.forms import CreateEventForm, TimetableWeeklySessionFormSet, \
    EditSessionForm, EditEventForm, EventsFormSet
from studioadmin.views.utils import StaffUserMixin

from timetable.models import Event, WeeklySession

logger = logging.getLogger(__name__)

EVENT_CHOICES_DICT = dict(Event.EVENT_CHOICES)


class WeeklySessionListView(LoginRequiredMixin, StaffUserMixin, ListView):

    model = WeeklySession
    template_name = 'studioadmin/timetable_sessions_list.html'
    context_object_name = 'sessions'

    def get_context_data(self):
        context = super(WeeklySessionListView, self).get_context_data()
        context['sessions_formset'] = TimetableWeeklySessionFormSet()
        context['sidenav_selection'] = 'timetable'
        return context

    def post(self, request, *args, **kwargs):
        session_forms = TimetableWeeklySessionFormSet(request.POST)

        if session_forms.has_changed():
            deleted_session_ids = []
            for form in session_forms:
                if form.has_changed() and 'DELETE' in form.changed_data:
                    session = WeeklySession.objects.get(id=form.instance.id)
                    deleted_session_ids.append(session.id)
                    # delete session
                    session.delete()

                msg = "Session{} {} {} been deleted".format(
                    's' if len(deleted_session_ids) > 1 else '',
                    ', '.join(["{}".format(id) for id in deleted_session_ids]),
                    'have' if len(deleted_session_ids) > 1 else 'has',
                )
            ActivityLog.objects.create(
                log="Session{plural} (id{plural} {ids}) {pluralhas} "
                    "been deleted by admin user {user}".format(
                        plural='s' if len(deleted_session_ids) > 1 else '',
                        pluralhas = 'have' if len(deleted_session_ids) > 1
                        else 'has',
                        ids=', '.join(
                            ["{}".format(id) for id in deleted_session_ids]
                        ),
                        user=request.user.username
                    )
            )
            messages.success(request, msg)
        else:
            messages.info(request, "No changes made")

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('studioadmin:timetable_sessions_list')


class EventListView(LoginRequiredMixin, StaffUserMixin, ListView):

    model = Event
    template_name = 'studioadmin/timetable_events_list.html'
    context_object_name = 'events'
    event_type = None

    def get_queryset(self):
        return Event.objects.filter(event_type=self.event_type)

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        context['events_formset'] = EventsFormSet(queryset=self.object_list)
        context['event_type'] = self.event_type
        context['event_type_title'] = EVENT_CHOICES_DICT[self.event_type]
        context['sidenav_selection'] = 'timetable'
        return context

    def post(self, request, *args, **kwargs):
        events_forms = EventsFormSet(request.POST)

        if events_forms.has_changed():
            deleted_event_ids = []
            updated_event_ids = []
            for form in events_forms:
                if form.has_changed():
                    if 'DELETE' in form.changed_data:
                        event = Event.objects.get(id=form.instance.id)
                        deleted_event_ids.append(event.id)
                        # delete event
                        event.delete()
                    else:
                        updated_event_ids.append(form.instance.id)
                        form.save()

            if deleted_event_ids:
                msg = "{}{} {} {} been deleted".format(
                    EVENT_CHOICES_DICT[self.event_type],
                    's' if len(deleted_event_ids) > 1 else '',
                    ', '.join(["{}".format(name) for name in deleted_event_ids]),
                    'have' if len(deleted_event_ids) > 1 else 'has',
                )
                ActivityLog.objects.create(
                    log="{event_type}{plural} (id{plural} {ids}) "
                        "{pluralhas} been deleted by admin user {user}".format(
                            event_type=EVENT_CHOICES_DICT[self.event_type],
                            plural='s' if len(deleted_event_ids) > 1 else '',
                            pluralhas = 'have' if len(deleted_event_ids) > 1
                            else 'has',
                            ids=', '.join(
                                ["{}".format(id) for id in deleted_event_ids]
                            ),
                            user=request.user.username
                        )
                )
            if updated_event_ids:
                msg = "{}{} {} {} been updated".format(
                    EVENT_CHOICES_DICT[self.event_type],
                    's' if len(updated_event_ids) > 1 else '',
                    ', '.join(["{}".format(id) for id in updated_event_ids]),
                    'have' if len(updated_event_ids) > 1 else 'has',
                )
                ActivityLog.objects.create(
                    log="{event_type}{plural} (id{plural} {ids}) "
                        "{pluralhas} been deleted by admin user {user}".format(
                            event_type=EVENT_CHOICES_DICT[self.event_type],
                            plural='s' if len(updated_event_ids) > 1 else '',
                            pluralhas = 'have' if len(updated_event_ids) > 1
                            else 'has',
                            ids=', '.join(
                                ["{}".format(id) for id in updated_event_ids]
                            ),
                            user=request.user.username
                        )
                )

            messages.success(request, msg)
        else:
            messages.info(request, "No changes made")

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('studioadmin:timetable_{}s_list'.format(self.event_type))


class CreateWeeklySessionView(LoginRequiredMixin, StaffUserMixin, CreateView):
    model = WeeklySession
    form_class = EditSessionForm
    template_name = 'studioadmin/add_weekly_session.html'

    def get_success_url(self):
        return reverse('studioadmin:timetable_sessions_list')


class CreateEventView(LoginRequiredMixin, StaffUserMixin, CreateView):
    model = Event
    form_class = CreateEventForm
    template_name = 'studioadmin/add_event.html'

    def get_context_data(self, **kwargs):
        event_type = self.kwargs['event_type']
        context = super(CreateEventView, self).get_context_data(**kwargs)
        context['event_type'] = event_type
        context['event_type_title'] = EVENT_CHOICES_DICT[event_type]
        return context

    def get_form_kwargs(self):
        kwargs = super(CreateEventView, self).get_form_kwargs()
        kwargs['event_type'] = self.kwargs['event_type']
        return kwargs

    def form_valid(self, form):
        event = form.save(commit=False)
        event.event_type = self.kwargs['event_type']
        event.save()
        return super(CreateEventView, self).form_valid(form)

    def get_success_url(self):
        return reverse(
            'studioadmin:timetable_{}s_list'.format(self.kwargs['event_type'])
        )


class WeeklySessionEditView(LoginRequiredMixin, StaffUserMixin, UpdateView):

    model = WeeklySession
    template_name = 'studioadmin/includes/weekly-session-modal.html'
    form_class = EditSessionForm

    def form_valid(self, form):
        form.save()
        if form.has_changed():
            messages.success(self.request, 'Saved!')
            form.save()
        else:
            messages.success(self.request, 'No changes made')
        return render(
            self.request, 'studioadmin/includes/weekly-session-edit-success.html'
            )


class EventEditView(LoginRequiredMixin, StaffUserMixin, UpdateView):

    model = Event
    template_name = 'studioadmin/includes/event-modal.html'
    form_class = EditEventForm
    # event_type = None

    def get_context_data(self, **kwargs):
        context = super(EventEditView, self).get_context_data(**kwargs)
        event_type = self.get_object().event_type
        context['event_type'] = event_type
        context['event_type_title'] = EVENT_CHOICES_DICT[event_type]
        return context

    def form_valid(self, form):
        form.save()
        if form.has_changed():
            messages.success(self.request, 'Saved!')
            form.save()
        else:
            messages.success(self.request, 'No changes made')
        return render(
                self.request, 'studioadmin/includes/event-edit-success.html'
            )

timetable/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render
from django.views.generic import ListView

from timetable.models import Event, WeeklySession
from timetable.utils import staff_required


class WeeklySessionListView(ListView):

    model = WeeklySession
    template_name = 'timetable/timetable_grid.html'
    context_object_name = 'sessions'

    def get_context_data(self, **kwargs):
        context = super(WeeklySessionListView, self).get_context_data(**kwargs)
        sessions_by_weekday = []
        for day in WeeklySession.DAY_CHOICES:
            sessions = WeeklySession.objects.filter(day=day[0])
            if sessions:
                sessions_by_weekday.append(
                    {'weekday': day[1], 'sessions': sessions}
                )
        context['sessions_by_weekday'] = sessions_by_weekday

        spaces = WeeklySession.objects.filter(full=False).exists()
        context['classes_with_spaces'] = spaces
        context['nav_section'] = 'timetable'
        return context


class EventListView(ListView):

    model = Event
    template_name = 'timetable/timetable_events.html'
    context_object_name = 'events'
    event_type = None

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        events = Event.objects.filter(
            show_on_site=True, event_type=self.event_type
        ).order_by('-date')
        context['events'] = events
        context['event_title'] = dict(Event.EVENT_CHOICES)[self.event_type]
        context['event_type'] = self.event_type
        context['nav_section'] = 'services'
        return context


@login_required
@staff_required
def toggle_spaces(request, session_id):
    session = WeeklySession.objects.get(id=session_id)
    session.full = not session.full
    session.save()
    return render(
        request, 'timetable/includes/spaces.txt', {'session': session}
    )

templates/timetable/timetable.html
{% extends "base.html" %}
{% load static %}
{% load timetabletags %}

{% block content %}

    <div class="container-fluid row">

        <h2 class="page-header">Timetable</h2>
        {% if sessions %}
        <div class="row">
            <div class="col-sm-12">

                <div class="panel panel-success">

                    <div class="table-responsive">
                        <table class="table timetable">
                            <thead>
                            <tr class="success">
                                <th>Day</th>
                                <th>Time</th>
                                <th>Class</th>
                                <th>Location</th>
                                <th>Block Information</th>
                                <th>Availability</th>
                                {% if request.user.is_staff %}<th></th>{% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for session in sessions %}
                                <tr>
                                    <td>{{ session.day | format_session_day }}</td>
                                    <td>{{ session.time| date:"H:i" }}</td>
                                    <td>{% if session.description %}
                                            <a href="#DescriptionModal" role="button" data-toggle="modal" class="description-link"
                                               data-title="{{ session.name }}"
                                               data-description="{{ session.description }}"
                                            >{{ session.name }}</a>
                                        {% else %}{{ session.name }}{% endif %}
                                    </td>
                                    <td>
                                        <a href="#LocationModal" role="button" data-toggle="modal" class="location-link"
                                           data-short_name="{{ session.location.short_name }}"
                                           data-full_name="{{ session.location.full_name }}"
                                           data-address="{{ session.location.address }}"
                                           data-map_url="{{ session.location.map_url }}"
                                                >{{ session.location }}</a>
                                    </td>
                                    <td>{{ session.block_info | linebreaks }}</td>
                                    <td id="spaces_{{ session.id }}">
                                        {% include 'timetable/includes/spaces.txt' %}
                                    </td>
                                    {% if request.user.is_staff %}
                                    <td>
                                        <button data-session_id="{{ session.id }}" class="toggle_spaces_button btn table-btn btn-info">Change spaces</button>
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td {% if request.user.is_staff %}colspan="7"{% else %}colspan="6"{% endif %}>
                                    {% if classes_with_spaces %}**There may be drop-in spaces available in these classes.<br/>{% endif %}
                                    <a href="{% url 'website:contact' %}?enq={{ session.id }}">Contact me</a> for further information.
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>



                </div>
            </div>
         </div>
        {% else %}
            <p>Coming soon</p>
        {% endif %}

    </div>

<!-- Description Modal HTML -->
<div id="DescriptionModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="description-title">Class Name</h4>
            </div>
            <div class="modal-body">
                <div id="description-text">Description</div>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>

<!-- Location Modal HTML -->
<div id="LocationModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="location-title">Short Name</h3>
            </div>
            <div class="modal-body">
                <h4 class="modal-title" id="location-full_name">Full Name</h4>
                <div id="location-address">Address</div>
                <iframe id="location-map" frameborder="0"></iframe>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>



{% endblock content %}

{% block extra_scripts %}
    {% if is_debug_on %}
       <script type='text/javascript' src="{% static 'timetable/js/underscore.js' %}"></script>
    {% else %}
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
   {% endif %}
    <script type='text/javascript' src="{% static 'timetable/js/ajax_timetable_spaces.js' %}"></script>
    <script src="{% static 'timetable/js/location_modal.js' %}"></script>
{% endblock %}

templates/timetable/timetable_clinics.html
{% extends "base.html" %}
{% load static %}
{% load timetabletags %}

{% block content %}

    <section id="timetable_page" class="transparent-bg">
        <div class="container">
           <div class="center wow fadeInDown">
                <h1>Timetable - Stretch Clinics</h1>
           </div>

        <ul class="classes-filter text-center">
                <li><a class="btn btn-fb-success-minor" href="{% url 'timetable:timetable' %}">Regular Classes</a></li>
                <li><a class="btn btn-fb-success" href="#">Stretch Clinics</a></li>
            </ul>

             {% include 'timetable/includes/clinic_data.html' %}
        </div>

    </section>


{% endblock content %}

{% block extra_scripts %}
    {% if is_debug_on %}
       <script type='text/javascript' src="{% static 'timetable/js/underscore.js' %}"></script>
    {% else %}
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
   {% endif %}
    <script src="{% static 'timetable/js/location_modal.js' %}"></script>
{% endblock %}

templates/timetable/timetable_events.html
{% extends "base.html" %}
{% load static %}
{% load timetabletags %}

{% block content %}

    <section id="timetable_page" class="transparent-bg">
        <div class="container">
           <div class="center wow fadeInDown">
                <h1>Timetable - {{ event_title }}s</h1>
           </div>

        <ul class="classes-filter text-center">
                <li><a class="btn btn-fb-success-minor" href="{% url 'timetable:timetable' %}">Regular Classes</a></li>
                <li><a class="btn {% if event_type == 'clinic' %}btn-fb-success{% else %}btn btn-fb-success-minor{% endif %}" href="{% url 'timetable:timetable_clinics' %}">Stretch Clinics</a></li>
                <li><a class="btn {% if event_type == 'workshop' %}btn-fb-success{% else %}btn btn-fb-success-minor{% endif %}" href="{% url 'timetable:timetable_workshops' %}">Workshops</a></li>
            </ul>

             {% include 'timetable/includes/event_data.html' %}
        </div>

    </section>


{% endblock content %}

{% block extra_scripts %}
    {% if is_debug_on %}
       <script type='text/javascript' src="{% static 'timetable/js/underscore.js' %}"></script>
    {% else %}
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
   {% endif %}
    <script src="{% static 'timetable/js/location_modal.js' %}"></script>
{% endblock %}

templates/timetable/timetable_grid.html
{% extends "base.html" %}
{% load static %}
{% load timetabletags %}

{% block content %}

    <section id="timetable_page" class="transparent-bg">
        <div class="container">
           <div class="center wow fadeInDown">
                <h1>Timetable - Regular Classes</h1>
           </div>

        <ul class="classes-filter text-center">
                <li><a class="btn btn-fb-success" href="#">Regular Classes</a></li>
                <li><a class="btn btn-fb-success-minor" href="{% url 'timetable:timetable_clinics' %}">Stretch Clinics</a></li>
                <li><a class="btn btn-fb-success-minor" href="{% url 'timetable:timetable_workshops' %}">Workshops</a></li>
            </ul>

        <div class="row">
        {% if sessions %}
            {% for weekday_sessions in sessions_by_weekday %}
                <div class="col-sm-6 col-xs-12">
                    <ul class="list-group text-center">
                        <li class="list-group-item list-group-item-timetable-heading">
                            <h4>{{ weekday_sessions.weekday }}</h4>
                        </li>
                        {% for session in weekday_sessions.sessions %}
                        <li class="list-group-item list-group-item-timetable">{{ session.time| date:"H:i" }}
                            <a href="#DescriptionModal" role="button"
                               data-toggle="modal"
                               class="description-link"
                               data-title="{{ session.name }}"
                               data-description="{{ session.description }}"
                               data-blockinfo="{{ session.block_info }}"
                               data-location="{{ session.location.full_name }}"
                               data-address="{{ session.location.address }}"
                            >{{ session.name }}</a> -
                            <a href="#LocationModal" role="button"
                               data-toggle="modal"
                               class="location-link"
                               data-short_name="{{ session.location.short_name }}"
                               data-full_name="{{ session.location.full_name }}"
                               data-address="{{ session.location.address }}"
                               data-map_url="{{ session.location.map_url }}"
                               data-spaces="{% if session in classes_with_spaces %}spaces**{% else %}full{% endif %}"
                            >{{ session.location }}</a>

                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}


        {% else %}
            <p>Coming soon</p>
        {% endif %}

        </div>
    </div>

<!-- Description Modal HTML -->
<div id="DescriptionModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="description-title">Class Name</h1>
            </div>
            <div class="modal-body">
                <div id="description-text">Description</div>
                <h2>Location</h2>
                <div id="location">Full Name</div>
                <div id="location-address">Address</div>
                <h2>Booking and Prices</h2>
                <div id="block_info-text">Block Info</div>
                <div class="top-space"><a class='btn btn-sm btn-fb-success-minor' href="{% url 'website:contact' %}">Contact</a> for availability and to book</div>

            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>

<!-- Location Modal HTML -->
<div id="LocationModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="location-title">Short Name</h3>
            </div>
            <div class="modal-body">
                <h4 class="modal-title" id="location-full_name">Full Name</h4>
                <div id="location-address">Address</div>
                <iframe id="location-map" frameborder="0"></iframe>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>




{% endblock content %}

{% block extra_scripts %}
    {% if is_debug_on %}
       <script type='text/javascript' src="{% static 'timetable/js/underscore.js' %}"></script>
    {% else %}
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
   {% endif %}
    <script type='text/javascript' src="{% static 'timetable/js/ajax_timetable_spaces.js' %}"></script>
    <script src="{% static 'timetable/js/location_modal.js' %}"></script>
{% endblock %}