flexibeast/urls.py
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

from accounts.views import CustomLoginView, data_privacy_policy, cookie_policy

from website.views import permission_denied

urlpatterns = [
    path(
        'studioadmin/', include('studioadmin.urls')
    ),
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('timetable/', include('timetable.urls')),
    path('testimonials/', include('reviews.urls')),
    path('page-not-available/', permission_denied, name='permission_denied'),
    path('accounts/profile/', include('accounts.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path(
        'data-privacy-policy/', data_privacy_policy, name='data_privacy_policy'
    ),
    path(
        'cookie-policy/', cookie_policy, name='cookie_policy'
    ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico/',
        RedirectView.as_view(url=settings.STATIC_URL+'favicon.ico',
                             permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

if settings.HEROKU:  # pragma: no cover
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

urlpatterns.append(path('', include('website.urls')))

gallery/urls.py
from django.conf import settings
from django.urls import path
from gallery.views import category_detail_view, CategoryListView, \
    CategoryUpdateView, gallery_menu_view, view_gallery, gallery_website_view

app_name = 'gallery'


urlpatterns = [
    # path('', gallery_menu_view, name='gallery'),
    path('', gallery_website_view, name='gallery'),
    path('album/<slug:slug>/', category_detail_view, name='category'),
    ##### VIEWS FOR STAFF USER ONLY #####
    # Category list view, show all categories in list, allow  for edit of
    # name and delete of entire category, add new category, links to category
    # detail views
    path('albums/', CategoryListView.as_view(), name='categories'),
    # Category detail view, show all images for edit/delete/add
    path(
        'albums/<int:pk>/', CategoryUpdateView.as_view(),
        name='edit_category'
    )
]


if settings.TESTING:
    urlpatterns.append(path('alternative_view/', view_gallery, name='alternative'))

studioadmin/urls.py
from django.urls import include, path, re_path
from django.views.generic import RedirectView

from gallery.views import CategoryListView, CategoryUpdateView
from studioadmin.views.activitylog import ActivityLogListView
from studioadmin.views.email_users import choose_users_to_email, \
    email_users_view
from studioadmin.views.timetable import WeeklySessionListView, \
    EventListView, WeeklySessionEditView, EventEditView, \
    CreateWeeklySessionView, CreateEventView
from studioadmin.views.users import UserListView
from studioadmin.views.website import PageListView, PageCreateView, \
    PageUpdateView


app_name = 'studioadmin'


urlpatterns = [
    path('users/', UserListView.as_view(), name="users"),
    path('users/email/', choose_users_to_email, name="choose_email_users"),
    path('users/email/emailform/', email_users_view,
        name="email_users_view"),
    path(
        'activitylog/', ActivityLogListView.as_view(), name='activitylog'
    ),
    #### GALLERY #####
    path(
        'gallery/albums/', CategoryListView.as_view(),
        name='gallery_categories'
    ),
    # Category detail view, show all images for edit/delete/add
    path(
        'gallery/albums/<int:pk>', CategoryUpdateView.as_view(),
        name='gallery_category_edit'
    ),
    #### WEBSITE PAGES #####
    path(
        'website-pages/',
        PageListView.as_view(), name='website_pages_list'
    ),
    path(
        'website-pages/new/', PageCreateView.as_view(), name='add_page'
    ),
    re_path(
        r'^website-pages/(?P<name>[\w\d//-]+)$',
        PageUpdateView.as_view(), name='edit_page'
    ),
    path(
        '',
        RedirectView.as_view(url='/studioadmin/classes/', permanent=True)
    ),
    #### TIMETABLE #####
    path(
        'timetable/regular-classes/',
        WeeklySessionListView.as_view(), name='timetable_sessions_list'
    ),
    path(
        'timetable/regular-classes/new',
        CreateWeeklySessionView.as_view(), name='timetable_session_add'
    ),
    path(
        'timetable/stretch-clinics/',
        EventListView.as_view(event_type='clinic'),
        name='timetable_clinics_list'
    ),
    path(
        'timetable/workshops/', EventListView.as_view(event_type='workshop'),
        name='timetable_workshops_list'
    ),
    path(
        'timetable/(<str:event_type>/new',
        CreateEventView.as_view(), name='timetable_event_add'
    ),
    path(
        'timetable/sessionedit/<int:pk>/',
        WeeklySessionEditView.as_view(), name='sessionedit'
    ),
    path(
        'timetable/edit/<int:pk>/',
        EventEditView.as_view(), name='eventedit'
    ),
]

website/urls.py
from django.urls import path, re_path

from website.views import about, classes, contact, home, page, \
    privacy_policy, restricted_page_not_logged_in, retreats, \
    stretch_clinics, workshops


app_name = 'website'


urlpatterns = [
    path('contact/', contact, name='contact'),
    path(
        'login-required/', restricted_page_not_logged_in,
        name='restricted_page_not_logged_in'
    ),
    path('about/', about, name='about'),
    path('classes/', classes, name='classes'),
    path('stretch-clinics/', stretch_clinics, name='stretch_clinics'),
    path('workshops/', workshops, name='workshops'),
    path('retreats/', retreats, name='retreats'),
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    re_path(r'^(?P<page_name>[\w\d//-]+)/$', page, name='page'),
    # path('', page, {'page_name': 'about'}, name='about'),
    path('', home, name='home'),
]

activitylog/models.py
from django.db import models
from django.utils import timezone

class ActivityLog(models.Model):

    timestamp = models.DateTimeField(default=timezone.now)
    log = models.TextField()

website/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.core.files.uploadedfile import InMemoryUploadedFile

from imagekit.models import ProcessedImageField


PAGE_LAYOUT_CHOICES = (
    ('no-img', 'No images'),
    ('1-img-top', 'One image, centred, top of page'),
    ('1-img-left', 'One image, left of text'),
    ('1-img-right', 'One image, right of text'),
)

MENU_CHOICES = (
    ('main', 'Separate link in main menu'),
    ('dropdown', 'Displayed under "More" dropdown menu')
)


class Page(models.Model):

    name = models.CharField(
        max_length=255, unique=True,
        help_text="A unique identifier for this page. Use lowercase, no "
                  "spaces.  Forward slash (/) and hyphens (-) are allowed."
    )
    menu_name = models.CharField(
        max_length=255,
        help_text="The heading to include in the top menu bar; if left "
                  "blank, will not be shown as a menu option.",
        null=True, blank=True
    )
    menu_location = models.CharField(
        max_length=8,
        choices=MENU_CHOICES,
        default='dropdown',
        help_text='NOTE: ONLY PAGES IN THE "MORE" DROPDOWN WILL BE DISPLAYED '
                  'ON THE SITE.'
    )
    heading = models.CharField(max_length=255, null=True, blank=True)
    layout = models.CharField(
        max_length=15, choices=PAGE_LAYOUT_CHOICES, default='no-img',
        help_text="It is recommended to use landscape-oriented pictures for "
                  "a single, top of page image.  If no image is checked as "
                  "'main', the first uploaded image will be used."
    )
    content = models.TextField('Content')
    restricted = models.BooleanField(
        default=False,
        help_text='Page only visible if user is logged in and has been given '
                  'permission'
    )
    active = models.BooleanField(
        default=False,
        help_text="Unselect if you don't want this page to be visible on "
                  "the site (irrespective of user permissions)"
    )

    class Meta:
        permissions = (
            ("can_view_restricted", "Can view restricted pages"),
        )

    def __str__(self):
        return "{} page content".format(self.name.title())

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        if ' ' in self.name:
            self.name = self.name.replace(' ', '-')
        super(Page, self).save()


class Picture(models.Model):

    image = ProcessedImageField(
        upload_to='website_pages',
        format='JPEG',
        options={'quality': 70},
        null=True, blank=True,
    )
    page = models.ForeignKey(
        Page, related_name='pictures', on_delete=models.CASCADE
    )
    main = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # delete old image file when replacing by updating the file
        try:
            this = Picture.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except:
            pass # when new photo then we do nothing, normal case
        super(Picture, self).save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        # delete the image from storage when deleting Picture object
        self.image.delete()
        super(Picture, self).delete(*args, **kwargs)


class RestrictedAccessTracker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    start_date = models.DateTimeField(default=timezone.now)

studioadmin/forms/activitylog_forms.py
# -*- coding: utf-8 -*-

from django import forms


class ActivityLogSearchForm(forms.Form):
    search = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search log text'
            }
        )
    )
    search_date = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                'id': "logdatepicker",
                'placeholder': "Search by log date",
                'style': 'text-align: center'
            },
            format='%d-%m-%y',
        ),
    )
    hide_empty_cronjobs = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={
            'class': "regular-checkbox",
            'id': 'hide_empty_cronjobs_id'
        }),
        initial='on'
    )

studioadmin/views/activitylog.py
import operator

from datetime import datetime
from functools import reduce

from django.contrib import messages
from django.db.models import Q
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from braces.views import LoginRequiredMixin

from studioadmin.forms import ActivityLogSearchForm
from studioadmin.views.utils import StaffUserMixin
from activitylog.models import ActivityLog


class ActivityLogListView(LoginRequiredMixin, StaffUserMixin, ListView):

    model = ActivityLog
    template_name = 'studioadmin/activitylog.html'
    context_object_name = 'logs'
    paginate_by = 20

    def get_queryset(self):

        empty_text = [
            'email_warnings job run; no unpaid booking warnings to send',
            'cancel_unpaid_bookings job run; no bookings to cancel'
        ]
        queryset = ActivityLog.objects.exclude(
            log__in=empty_text
        ).order_by('-timestamp')

        reset = self.request.GET.get('reset')
        search_submitted =  self.request.GET.get('search_submitted')
        search_text = self.request.GET.get('search')
        search_date = self.request.GET.get('search_date')
        hide_empty_cronjobs = self.request.GET.get('hide_empty_cronjobs')

        if reset or (not (search_text or search_date) and hide_empty_cronjobs) \
                or (not reset and not search_submitted):
            return queryset

        if not hide_empty_cronjobs:
            queryset = ActivityLog.objects.all().order_by('-timestamp')

        if search_date:
            try:
                search_date = datetime.strptime(search_date, '%d-%b-%Y')
                start_datetime = search_date
                end_datetime = search_date.replace(
                    hour=23, minute=59, second=59, microsecond=999999
                )
                queryset = queryset.filter(
                    Q(timestamp__gte=start_datetime) &
                    Q(timestamp__lte=end_datetime)
                ).order_by('-timestamp')
            except ValueError:
                messages.error(
                    self.request, 'Invalid search date format.  Please select '
                    'from datepicker or enter using the format dd-Mmm-YYYY'
                )
                return queryset

        if search_text:
            search_words = search_text.split()
            search_qs = reduce(
                operator.and_, (Q(log__icontains=x) for x in search_words)
            )
            queryset = queryset.filter(search_qs)

        return queryset

    def get_context_data(self):
        context = super(ActivityLogListView, self).get_context_data()
        context['sidenav_selection'] = 'activitylog'

        search_submitted =  self.request.GET.get('search_submitted')
        hide_empty_cronjobs = self.request.GET.get('hide_empty_cronjobs') \
        if search_submitted else 'on'

        search_text = self.request.GET.get('search', '')
        search_date = self.request.GET.get('search_date', None)
        reset = self.request.GET.get('reset')
        if reset:
            hide_empty_cronjobs = 'on'
            search_text = ''
            search_date = None
        form = ActivityLogSearchForm(
            initial={
                'search': search_text, 'search_date': search_date,
                'hide_empty_cronjobs': hide_empty_cronjobs
            })
        context['form'] = form

        return context

studioadmin/views/utils.py
from functools import wraps

from django.urls import reverse
from django.shortcuts import HttpResponseRedirect


def staff_required(func):
    def decorator(request, *args, **kwargs):
        if request.user.is_staff:
            return func(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('permission_denied'))
    return wraps(func)(decorator)


class StaffUserMixin(object):

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            return HttpResponseRedirect(reverse('permission_denied'))
        return super(StaffUserMixin, self).dispatch(request, *args, **kwargs)

templates/studioadmin/add_stretch_clinic.html
{% extends "studioadmin/base.html" %}
{% load static %}
{% load commontags timetabletags %}

{% block studioadmincontent %}

{{ form.media }}

<div class="studioadmin-container">

   <div class="panel panel-success">
        <div class="panel-heading">
            <h2 class="panel-title">Adding new Stretch Clinic</h2>
        </div>

        <div class="panel-body panel-default">

        <form id="clinic-form" method='post' class="form" role="form">

                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {% for field in form %}
                        <div class="row">
                         <div class="col-xs-12">
                             <div class="col-xs-3">{{ field.label_tag }}</div>
                             <div class="col-xs-9 input-group">
                                 {% if field.name == 'cost' %}<span class="input-group-addon">£</span>{% endif %}
                                 {{ field }}
                                 {% if field.name == 'cost' %}<span class="input-group-addon">per hour</span>{% endif %}
                                 <label for='id_{{ field.name }}'></label></div>

                            {% if field.errors %}
                                <div class="form-error col-xs-9 col-xs-offset-3">
                                    {% for error in field.errors %}
                                        <span class="fa fa-exclamation-triangle"></span>{{ error|escape }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        </div>
                    {% endfor %}

                </div>
                <div>
                    <input type="submit" class="btn btn-success" value="Save" />
                </div>
        </form>
    </div>

   </div>
</div>
{% endblock %}

templates/studioadmin/base.html
{% extends "base.html" %}

{% load static %}
{% load socialaccount %}
{% providers_media_js %}


{% block extra_head %}
        <link href="{% static 'studioadmin/css/studioadmin.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar-items %}
         <li class="dropdown {% if sidenav_selection == 'page_list' or sidenav_selection == 'add_page' %}active{% endif %}">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Website Pages <span class="fa fa-caret-down"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'studioadmin:website_pages_list' %}">View and edit pages</a></li>
            <li><a href="{% url 'studioadmin:add_page' %}">Add new page</a></li>
          </ul>
        </li>
        <li class="dropdown {% if sidenav_selection == 'timetable' %}active{% endif %}">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Timetables <span class="fa fa-caret-down"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'studioadmin:timetable_sessions_list' %}">Regular Classes</a></li>
            <li><a href="{% url 'studioadmin:timetable_clinics_list' %}">Stretch Clinics</a></li>
              <li><a href="{% url 'studioadmin:timetable_workshops_list' %}">Workshops</a></li>
          </ul>
        </li>
        <li {% if sidenav_selection == 'gallery' %}class="active"{% endif %}>
            <a href="{% url 'studioadmin:gallery_categories' %}">Gallery</a>
        </li>
         <li class="dropdown {% if sidenav_selection == 'users' or sidenav_selection == 'block_bookings' or sidenav_selection == 'email_users' %}active{% endif %}">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Students <span class="fa fa-caret-down"></span></a>
          <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'studioadmin:users' %}">Registered users</a></li>
          {% if booking_on %}
                <li><a href="{% url 'studioadmin:block_bookings' %}">Block bookings</a></li>
          {% endif %}
                <li><a href="{% url 'studioadmin:choose_email_users' %}">Bulk email to students</a></li>
          </ul>
      </li>

    <li {% if sidenav_selection == 'activitylog' %}class="active"{% endif %}><a href="{% url 'studioadmin:activitylog' %}">
    Activity Log</a></li>


{% endblock %}

{% block admin-nav %}{% endblock admin-nav %}

{% block content %}
    <div class="studioadmin-container">
        <h1 style="color: #000">Admin</h1>
    </div>
            {% block studioadmincontent %}{% endblock %}

{% endblock %}


{% block footer %}
    <div class="studioadmin-footer">
        <div class="container-fluid">
            <div class="row footer_box">
                <div class="footer-fb pull-right">
                    <div class="footer-credit">Site developed by <a href="https://twitter.com/rebkwok" target="_blank" style="color: #0B0B61">Becky Smith</a></div>
                </div>

            </div>
        </div>
    </div>
{% endblock footer %}

templates/studioadmin/email_users_confirmation.html
{% extends 'studioadmin/base.html' %}

{% block studioadmincontent %}
<div class="container-fluid row">
    <div class="col-sm-12">
        <div>
            <h4>Your email has been sent!</h4>
        </div>
    </div>
</div>

{% endblock %}

templates/studioadmin/timetable_events_list.html
{% extends "studioadmin/base.html" %}
{% load static %}
{% load commontags timetabletags websitetags %}

{% block studioadmincontent %}
    <div class="studioadmin-container">
        <h2>{{ event_type_title|title}}s
            <a class="btn btn-success pull-right"
               href="{% url 'studioadmin:timetable_event_add' event_type %}" >Add new {{ event_type_title|lower }}</a></h2>
                <div class="panel">
                    <form class="form-horizontal" method="post" action="">
                    {% csrf_token %}
                    <div class="table-responsive">
                        <table class="table tablesorter" id="sortTable">
                            <thead>
                            <tr class="success">
                                <th>Date </br><span class="studioadmin-help">Click to edit</span></th>
                                <th>Name</th>
                                <th>Location</th>
                                <th>Max spaces</th>
                                <th>Spaces</th>
                                <th>Show on site</th>
                                <th class="table-center">Delete</th>
                            </tr>
                            </thead>
                            <tbody>

                            <!-- Modal -->
                            <div class="modal fade" id="EventModal" tabindex="-1" role="dialog" aria-labelledby="EventModalLabel"></div>
                            <!-- /.modal -->

                            {{ events_formset.management_form }}
                            {% for event in events_formset %}
                                <span class=hide>{{ event.id }}</span>
                                <tr>
                                    <td class="studioadmin-tbl"><a class="eventedit" href="#" data-form="{% url 'studioadmin:eventedit' event.instance.id %}" title="edit {{ event_type}}">{{ event.instance.date | date:"D d M Y" }}</a></td>
                                    <td class="studioadmin-tbl">{{ event.instance.short_name }}
                                    <td class="studioadmin-tbl">{{ event.instance.location.short_name }}</td>
                                    <td class="studioadmin-tbl">{{ event.instance.max_spaces }}</td>
                                    <td class="studioadmin-tbl">{{ event.instance.spaces }}</td>
                                    <td class="studioadmin-tbl table-center">{{ event.show_on_site }}<label for={{ event.show_on_site_id }}></label></td>
                                    <td class="studioadmin-tbl table-center">{{ event.DELETE }}<label for={{ event.DELETE_id }}></label>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td class="studioadmin-tbl">
                                    <input class="btn btn-success" name="formset_submitted" type="submit" value="Save" />
                                </td>
                                <td colspan="5"></td>
                                <td class="studioadmin-tbl table-center">
                                    <input class="btn btn-danger" name="formset_submitted" type="submit" value="Delete selected" />
                                </td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                    </form>

                    </div>
                </div>

{% endblock studioadmincontent %}

{% block extra_scripts %}
{#http://malsup.github.com/jquery.form.js#}
<script src="{% static 'timetable/js/jquery.form.js' %}"></script>
<script>
    $(".eventedit").click(function(ev) { // for each edit url
        ev.preventDefault(); // prevent navigation
        var url = $(this).data("form"); // get the form url
        $("#EventModal").load(url, function() { // load the url into the modal
            $(this).modal('show'); // display the modal on url load
        });

        return false; // prevent the click propagation
    });

</script>
{% endblock %}

templates/studioadmin/timetable_sessions_list.html
{% extends "studioadmin/base.html" %}
{% load static %}
{% load commontags timetabletags websitetags %}

{% block studioadmincontent %}
    <div class="studioadmin-container">

        <h2>Regular Weekly Classes <a class="btn btn-success pull-right" href="{% url 'studioadmin:timetable_session_add' %}" >Add new class</a></h2>
                <div class="panel">
                    <form class="form-horizontal" method="post" action="">
                    {% csrf_token %}
                    <div class="table-responsive">
                        <table class="table tablesorter" id="sortTable">
                            <thead>
                            <tr class="success">
                                <th>Day</th>
                                <th>Time</th>
                                <th>Class name</br><span class="studioadmin-help">Click to edit</span></th>
                                <th>Location</th>
                                <th class="table-center">Delete class</th>
                            </tr>
                            </thead>
                            <tbody>

                            <!-- Modal -->
                            <div class="modal fade" id="SessionModal" tabindex="-1" role="dialog" aria-labelledby="SessionModalLabel"></div>
                            <!-- /.modal -->

                            {{ sessions_formset.management_form }}
                            {% for weeklysession in sessions_formset %}
                                <span class=hide>{{ weeklysession.id }}</span>
                                <tr>
                                    <td class="studioadmin-tbl">{{ weeklysession.instance.day|format_session_day_long }}</td>
                                    <td class="studioadmin-tbl">{{ weeklysession.instance.time|date:"H:i" }}</td>
                                    <td class="studioadmin-tbl"><a class="sessionedit" href="#" data-form="{% url 'studioadmin:sessionedit' weeklysession.instance.id %}" title="edit session">{{ weeklysession.instance.name }}</a></td>
                                    <td class="studioadmin-tbl">{{ weeklysession.instance.location.short_name }}</td>
                                    <td class="studioadmin-tbl table-center">{{ weeklysession.DELETE }}<label for={{ weeklysession.DELETE_id }}></label>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="4"></td>
                                <td class="studioadmin-tbl table-center">
                                    <input class="btn btn-danger" name="formset_submitted" type="submit" value="Delete selected" />
                                </td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                    </form>

                    </div>
                </div>

{% endblock studioadmincontent %}

{% block extra_scripts %}
{#http://malsup.github.com/jquery.form.js#}
<script src="{% static 'timetable/js/jquery.form.js' %}"></script>
<script>
    $(".sessionedit").click(function(ev) { // for each edit url
        ev.preventDefault(); // prevent navigation
        var url = $(this).data("form"); // get the form url
        $("#SessionModal").load(url, function() { // load the url into the modal
            $(this).modal('show'); // display the modal on url load
        });

        return false; // prevent the click propagation
    });

</script>
{% endblock %}

templates/studioadmin/website_page_list.html
{% extends "studioadmin/base.html" %}
{% load static %}
{% load commontags websitetags %}

{% block studioadmincontent %}
    <div class="studioadmin-container">

        <h2>Website Pages</h2>
                <div class="panel">
                    <form class="form-horizontal" method="post" action="">
                    {% csrf_token %}
                    <div class="table-responsive">
                        <table class="table tablesorter" id="sortTable">
                            <thead>
                            <tr class="success">
                                <th>Page name</br><span class="studioadmin-help">Click to edit</span></th>
                                <th>Page heading</th>
                                <th>Menu name</th>
                                <th>Layout</th>
                                <th>Permission to view</th>
                                <th>Page visible</th>
                                <th>View on site</th>
                                <th class="table-center">Delete page</th>
                            </tr>
                            </thead>
                            <tbody>

                            {{ pages_formset.management_form }}
                            {% for page in pages_formset %}
                                <span class=hide>{{ page.id }}</span>
                                <tr>
                                    <td class="studioadmin-tbl"><a href="{% url 'studioadmin:edit_page' page.instance.name %}">{{ page.instance.name }}</a></td>
                                    <td class="studioadmin-tbl">{{ page.instance.heading }}</td>
                                    <td class="studioadmin-tbl">{{ page.instance.menu_name }}</td>
                                    <td class="studioadmin-tbl">{{ page.instance.layout | format_layout }}</td>
                                    <td class="studioadmin-tbl">{%  if page.instance.restricted %}<span class="not-confirmed">RESTRICTED</span>{% else %}ALL{% endif %}</td>
                                    <td class="studioadmin-tbl">{%  if page.instance.active %}LIVE{% else %}<span class="not-confirmed">HIDDEN</span>{% endif %}</td>
                                    <td class="studioadmin-tbl table-center"><a href="{% url 'website:page' page.instance.name %}"><span class="fa fa-link"></span></a></td>
                                    <td class="studioadmin-tbl table-center">{{ page.DELETE }}<label for={{ page.DELETE_id }}></label>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td class="studioadmin-tbl" colspan="8">
                                    <a class="btn btn-success" href="{% url 'studioadmin:add_page' %}" >Add new page</a>
                                    <input class="btn btn-danger pull-right" name="formset_submitted" type="submit" value="Delete selected pages" /></td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                    </form>

                    </div>
                </div>

{% endblock studioadmincontent %}